dist: xenial
language: python
python:
- '3.4'
env:
  matrix:
  - TEST_IMAGE=centos-7-base
  - TEST_IMAGE=ubuntu-14.04-base
  - TEST_IMAGE=ubuntu-14.04-oe
  - TEST_IMAGE=ubuntu-16.04-base
  - TEST_IMAGE=ubuntu-16.04-oe
  - TEST_IMAGE=ubuntu-18.04-base
  - TEST_IMAGE=ubuntu-18.04-oe
  global:
  - secure: VS/awLpGRtJ5usdzpwUO0NyOqfAI3AF1VtEnrv+/kZT2ZkTD5VNHpdHCCVieQoJMFY/Pkl45CDKkfFsrBYNMEjRI/Y37WgeOEp0+JzppMTIoQE/OBpRtzbtm+Z63BW/YUxVy1c8T8nwSmCEVYmWxfr9tgNnqCOz8Kqrfqpyz9JCa8GXclGNs/ewbhzbuTaYtiyBl3C0AsVz4PakfkXy6zr9gStfj+K7+D62OJg09fKw/+m7VBp229l3EECBjIDYetH1ZXMDnEvnwKsmKhBBcDcitw6AqeY3/6ne4vF9mkLOJ0NDc3mQQpOqPFCjOU2U7i02p8mi4ip50OpZi01iEQSUPnXwNd6LWIcfvK5jTVJOTqrIT/QxIFeEXThKGeU46kyWqafT1VMPoQgDeBXUFzz4QtcRRpOlk7UL+pybr0LZSY1+Zgb9ms2zfFfFJajZ+EScB/wbZnnCbYDS7G+uInhg0h/pe1Ee0W1GwPxV+475qz+1n+nEI3Kf3qPmT10vhcO5sOp9Gw9lirNYmaX8gv0ZefD7y693mSE93FUq9iVGXUpHwesCw+yC9WNgQImzwZSqjwQUcCazBapwv30WGY9P/ELpcoVc+oQP9z9zORlYGUo+PzfJPFUOXrnl/lc14IvXFeDZVJCBNSr/K+K+8pMiO4Os0awvhckzVFB2zWTQ=
  - secure: JjZHrFwLIoSOjcdnltmg3BOTFH0xv9WyU4/wI5D8vfXq4jy5Fw1PRCeH4ME6R/JHxobSGSixaxbBSvq2gVobDv57ZdrfXpJVRI7vFoyOby4KRYKhR2EilmJ5nuYhALol/kLdr+sMyvLPy6Lxp9+XYpfQ6zJDc+6+OvFqpd6DWXy4DnPyRXlQzRE4T/0WDO0JhxS1abyx1FHpLetHiN4g0b0ch3LuqWnBRLQNYAE2LPbmUNF4UpjigitUcBkXd2LEInS5PZMoLvpDjewEEaKnoMrbdY7sn+jaIvlBACSfSvdMIV4Wi5ohj+SKHNupgP7nN0gVRtNs8EjeWnvNrvjRok2btTOjRllrxeQBcYllWJ2CcC4otDeGl0LpqgGpCJcJDCWShptV2X1el79YdBI8VOh7UtX02V/5Jmmu7oJw+clqoADFZ4UnG8+npiHqP5Ky6resEYiOZjMLRxM7RgjgGTbc1vxNwhwx0w9eDcQWDjRXLRQ3z66tDEcJ5C73+K+nktntGoFCZLTsw9z8F7XnL2qm1rkZU80usMGEIUA9+GUFhTkfW3w/3gaoSyf8F8+Vz9+KDVO5jRdcGNEEJoZ+FN12neT5Xy5wz/2+3TlXtsiiOjjFGqPd9Tyzo6VLRhQTY8kPSc/Rd1ag+rVh9JIxsvtXZM8F3zEl1zSF9gtFSGM=
before_install:
- "./ci/prepare.sh"
- 'echo ''{ "features": { "buildkit": true } }'' | sudo tee /etc/docker/daemon.json

'
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
install:
- pip3 install coverage
- pip3 install coveralls
- pip3 install requests
before_script:
- printf '\nimport coverage\ncoverage.current_coverage = coverage.process_startup()\n'
  >> "/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/lib/python${TRAVIS_PYTHON_VERSION}/sitecustomize.py"
- rm -f .coverage-report.*
script: COVERAGE_PROCESS_START=${TRAVIS_BUILD_DIR}/.coveragerc python3 -m unittest discover -vb -s ci/ -k PyrexImage_$(echo $TEST_IMAGE | sed 's/\W/_/g')
after_success:
- coverage3 combine
- coveralls
deploy:
- provider: script
  skip_cleanup: true
  script: "./ci/deploy_docker.py --login $TEST_IMAGE"
  on:
    all_branches: true
    condition: "$TRAVIS_PULL_REQUEST == false && ($TRAVIS_BRANCH == master || $TRAVIS_TAG
      =~ ^v[0-9].*$)"
- provider: script
  skip_cleanup: true
  script: "./ci/deploy_docker.py --login $TEST_IMAGE:next"
  on:
    branch: next
